# Generated by Django 4.0.1 on 2022-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailChimp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimpCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
            ],
        ),
    ]
